import './globals.css';
import type { Metadata } from 'next';
import GlobalProvider from './GlobalProvider';
import { PropsWithChildren } from 'react';


export const metadata: Metadata = {
	title: 'Coders-Factory',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang='en'>
			<body>
				<GlobalProvider>{children}</GlobalProvider>
			</body>
		</html>
	);
}
