import Sidebar from '@/components/Sidebar';
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Coders-Factory',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body>
				<Sidebar />
				{children}
			</body>
		</html>
	);
}
